// generated by ChatGPT
package org.firstinspires.ftc.teamcode.testing;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorSimple.Direction;
import com.qualcomm.robotcore.util.ElapsedTime;

@TeleOp(name = "Slide Profile Test", group = "Test")
public class SlideProfileTest extends LinearOpMode {

  @Override
  public void runOpMode() {
    DcMotor slideLeft = hardwareMap.dcMotor.get("lu");
    DcMotor slideRight = hardwareMap.dcMotor.get("ru");

    slideLeft.setDirection(Direction.FORWARD);
    slideRight.setDirection(Direction.REVERSE);

    slideLeft.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
    slideRight.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);

    slideLeft.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    slideRight.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);

    slideLeft.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
    slideRight.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

    waitForStart();

    ElapsedTime timer = new ElapsedTime();
    double lastTime = 0;
    double lastPos = 0;
    double maxVel = 0;
    double maxAccel = 0;

    boolean prevPress = false;

    while (opModeIsActive()) {
      boolean held = gamepad1.x;

      if (held) {
        slideLeft.setPower(1);
        slideRight.setPower(1);

        double now = timer.seconds();
        double curPos = slideRight.getCurrentPosition();
        double dt = now - lastTime;

        if (dt > 0.01) {
          double velocity = (curPos - lastPos) / dt;
          double accel = (velocity - maxVel) / dt;

          maxVel = Math.max(maxVel, Math.abs(velocity));
          maxAccel = Math.max(maxAccel, Math.abs(accel));

          lastTime = now;
          lastPos = curPos;
        }

        telemetry.addLine("Recording... Hold X");
        telemetry.update();
      } else {
        slideLeft.setPower(0);
        slideRight.setPower(0);

        if (prevPress) {
          telemetry.addData("Max Velocity (ticks/s)", maxVel);
          telemetry.addData("Max Acceleration (ticks/s^2)", maxAccel);
          telemetry.addLine("Release detected, values locked");
          telemetry.update();
        } else {
          telemetry.addLine("Press and hold X to test");
          telemetry.addData("Max Velocity (ticks/s)", maxVel);
          telemetry.addData("Max Acceleration (ticks/s^2)", maxAccel);
        }
      }

      prevPress = held;
      telemetry.addData("Max Velocity (ticks/s)", maxVel);
      telemetry.addData("Max Acceleration (ticks/s^2)", maxAccel);
      telemetry.update();
    }
  }
}
