// generated by ChatGPT
package org.firstinspires.ftc.teamcode.subsystems;

import com.acmerobotics.dashboard.config.Config;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotor.RunMode;
import com.qualcomm.robotcore.hardware.DcMotor.ZeroPowerBehavior;
import com.qualcomm.robotcore.hardware.DcMotorSimple.Direction;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.TouchSensor;
import com.qualcomm.robotcore.util.ElapsedTime;

@Config
public class VerticalSlides {

  public static int TRANSFER = 0;
  public static int BAR_PLACE_TELEOP = 800;
  public static int BAR_PLACE_UNDER = 300;
  public static int UP_AUTO = 1850;
  public static int UP = 2050;
  public static int LOWER_BUCKET = 700;

  public static double kp = 0.008;
  public static double ki = 0.00028;
  public static double kd = 0.0004;
  public static double kV = 1.0 / 2650; // Replace 1833 with your measured max velocity if known
  public static double kA = 0.0;
  public static double KG = 0.01;

  public static double MAX_VELOCITY = 2650; // ticks/sec
  public static double MAX_ACCEL = 100000;    // ticks/sec^2

  private final ElapsedTime timer = new ElapsedTime();
  private double lastError = 0;
  private double integralSum = 0;
  private double currentVelocity = 0;
  private double acceleration = 0;

  private int offset = 0;
  private int targetPos = TRANSFER;
  public int position = 0;

  public final DcMotor slideLeft;
  public final DcMotor slideRight;
  public final TouchSensor magLim;

  public VerticalSlides(LinearOpMode opMode) {
    HardwareMap hardwareMap = opMode.hardwareMap;

    slideLeft = hardwareMap.dcMotor.get("lu");
    slideRight = hardwareMap.dcMotor.get("ru");

    slideLeft.setDirection(Direction.FORWARD);
    slideRight.setDirection(Direction.REVERSE);

    slideLeft.setZeroPowerBehavior(ZeroPowerBehavior.BRAKE);
    slideRight.setZeroPowerBehavior(ZeroPowerBehavior.BRAKE);

    slideLeft.setMode(RunMode.RUN_WITHOUT_ENCODER);
    slideRight.setMode(RunMode.RUN_WITHOUT_ENCODER);

    magLim = hardwareMap.touchSensor.get("mag");
  }

  public void setMode(RunMode mode) {
    slideLeft.setMode(mode);
    slideRight.setMode(mode);
  }

  public void setPower(double pow) {
    slideLeft.setPower(pow);
    slideRight.setPower(pow);
  }

  public void setTarget(int target) {
    if (target != this.targetPos) {
      this.targetPos = target;
      timer.reset();
      integralSum = 0;
      lastError = 0;
    }
  }

  public int getTarget() {
    return this.targetPos;
  }

  private void updatePosition() {
    int curPos = this.slideRight.getCurrentPosition();
    if (this.magLim.isPressed()) {
      this.offset = curPos - VerticalSlides.TRANSFER;
    }
    this.position = curPos - this.offset;
  }

  public boolean atTarget() {
    return atTarget(30);
  }

  public boolean atTarget(int threshold) {
    return Math.abs(this.position - this.targetPos) < threshold;
  }

  public boolean atSetTarget(int threshold, int pos) {
    return Math.abs(this.position - pos) < threshold;
  }

  // This replaces your original updatePIDControl, but keeps the name
  public double updatePIDControl() {
    updatePosition();
    double dt = timer.seconds();
    timer.reset();

    double error = targetPos - position;

    // PID calculations
    integralSum += error * dt;
    double derivative = (error - lastError) / dt;
    lastError = error;

    // Motion profiling calculations
    double stoppingDist = (currentVelocity * currentVelocity) / (2.0 * MAX_ACCEL);
    if (Math.abs(error) < stoppingDist) {
      acceleration = -Math.signum(currentVelocity) * MAX_ACCEL;
    } else {
      acceleration = Math.signum(error) * MAX_ACCEL;
    }

    currentVelocity += acceleration * dt;

    double maxVel = Math.sqrt(2.0 * MAX_ACCEL * Math.abs(error));
    currentVelocity = Math.min(Math.abs(currentVelocity), maxVel) * Math.signum(currentVelocity);

    if (Math.abs(error) < 200) {
      currentVelocity = Math.max(-200, Math.min(200, currentVelocity));
    }

    if (Math.abs(currentVelocity) > MAX_VELOCITY) {
      currentVelocity = Math.signum(currentVelocity) * MAX_VELOCITY;
    }

    // Final power output
    double feedforward = (kV * currentVelocity) + (kA * acceleration) + KG;
    double feedback = (kp * error) + (kd * derivative) + (ki * integralSum);
    double power = feedforward + feedback;

    power = Math.max(-1.0, Math.min(1.0, power));
    setPower(power);
    return power;
  }
}
